name: Creating a Keyboard Oriented Puzzle Game for Flutter

type: flutter

steps:
  - name: Step 1 - Introduction
    directory: step_01
    has_solution: false
  - name: Step 2 - Adding a new FocusNode
    directory: step_02
    has_solution: true
  - name: Step 3 - Intents and Shortcuts
    directory: step_03
    has_solution: true
  - name: Step 4 - Actions
    directory: step_04
    has_solution: true
  - name: Step 5 - Setting up Game Page
    directory: step_05
    has_solution: true
  - name: Step 6 - Game Page Actions
    directory: step_06
    has_solution: true
  - name: Step 7 - Increasing the Gamification
    directory: step_07
    has_solution: true
  - name: Step 8 - The End
    directory: step_08
    has_solution: false